-   id: check-fvm
    name: Check if FVM is install
    language: script
    entry: check-fvm

-   id: fvm-format
    name: Dart code formatting through FVM
    entry: fvm-analyze
    language: script
    files: \.dart$

-   id: fvm-analyze
    name: Flutter code analyzing through FVM
    language: script
    entry: fvm-format
    files: \.dart$